DROP TABLE IF EXISTS Mascota;

CREATE TABLE IF NOT EXISTS Mascota (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  fecha_nac TIMESTAMP NOT NULL,
  raza VARCHAR(255) NOT NULL,
  peso DOUBLE NOT NULL,
  tiene_chip BOOLEAN NOT NULL,
  url_foto VARCHAR(255) NOT NULL
);
